name: Sample CI Workflow
run-name: ${{ github.actor }} is awesome!

on:
  push:
    branches:
      - "main"

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: say hellow
        run: |
          echo "Hello from github actions"
